const fs = require('fs');
const data = require('../../public/data/module-5/kec_sumatra.json');
const rawInput = `PANCUNG SOAL
RANAH PESISIR
LENGAYANG
BATANG KAPAS
IV JURAI
BAYANG
KOTO XI TARUSAN
SUTERA
LINGGO SARI BAGANTI
LUNANG
BASA AMPEK BALAI
IV NAGARI BAYANG UTARA
AIRPURA
RANAH AMPEK HULU
SILAUT
PANTAI CERMIN
LEMBAH GUMANTI
PAYUNG SEKAKI
LEMBANG JAYA
GUNUNG TALANG
BUKIT SUNDI
KUBUNG
X KOTO SINGKARAK
X KOTO DIATAS
JUNJUNG SIRIH
HILIRAN GUMANTI
TIGO LURAH
DANAU KEMBAR
X KOTO
BATIPUH
RAMBATAN
LIMA KAUM
TANJUNG EMAS
LINTAU BUO
SUNGAYANG
SUNGAI TARAB
PARIANGAN
PADANG GANTING
LINTAU BUO UTARA
BATIPUAH SELATAN
LUBUK ALUNG
BATANG ANAI
NAN SABARIS
2 X 11 ENAM LINGKUNG
VII KOTO SUNGAI SARIK
V KOTO KAMPUNG
SUNGAI GARINGGING
SUNGAI LIMAU
IV KOTO AUR MALINTANG
ULAKAN TAPAKIH
SINTUAK TOBOH GADANG
PADANG SAGO
BATANG GASAN
V KOTO TIMUR
2 X 11 KAYU TANAM
PATAMUAN
ENAM LINGKUNG
TANJUNG MUTIARA
LUBUK BASUNG
TANJUNG RAYA
MATUR
IV KOTO
BANUHAMPU
AMPEK ANGKEK
BASO
TILATANG KAMANG
PALUPUH
PELEMBAYAN
SUNGAI PUA
AMPEK NAGARI
CANDUNG
KAMANG MAGEK
MALALAK
SULIKI
GUGUAK
PAYAKUMBUH
LUAK
HARAU
PANGKALAN KOTO BARU
KAPUR IX
GUNUANG OMEH
LAREH SAGO HALABAN
SITUJUAH LIMO NAGARI
MUNGKA
BUKIK BARISAN
AKABILURU
BONJOL
LUBUK SIKAPING
PANTI
MAPAT TUNGGUL
DUO KOTO
TIGO NAGARI
RAO
MAPAT TUNGGUL SELATAN
SIMPANG ALAHAN MATI
PADANG GELUGUR
RAO UTARA
RAO SELATAN
PAGAI UTARA
SIPORA SELATAN
SIBERUT SELATAN
SIBERUT UTARA
SIBERUT BARAT
SIBERUT BARAT DAYA
SIBERUT TENGAH
SIPORA UTARA
SIKAKAP
PAGAI SELATAN
SANGIR
SUNGAI PAGU
KOTO PARIK GADANG
SANGIR JUJUAN
SANGIR BATANG HARI
PAUH DUO
SUNGAIBEREMAS
LEMBAH MELINTANG
PASAMAN
TALAMAU
KINALI
GUNUNGTULEH
RANAH BATAHAN
KOTO BALINGKA
SUNGAIAUR
LUHAK NAN DUO
SASAK RANAH PESISIR
PADANG SELATAN
PADANG TIMUR
PADANG BARAT
PADANG UTARA
BUNGUS TELUK KABUNG
LUBUK BEGALUNG
LUBUK KILANGAN
PAUH
KURANJI
NANGGALO
KOTO TANGAH
LUBUK SIKARAH
TANJUNG HARAPAN
PADANG PANJANG TIMUR
PADANG PANJANG BARAT
GUGUAK PANJANG
MANDIANGIN K. SELAYAN
AUR BIRUGO TIGO BALEH
PAYAKUMBUH BARAT
PAYAKUMBUH TIMUR
PAYAKUMBUH SELATAN
PARIAMAN TENGAH
PARIAMAN UTARA
PARIAMAN SELATAN
PARIAMAN TIMUR`;

const targetSet = new Set(rawInput.split('\n').map(s => s.trim().toUpperCase()));

const matchedNames = new Set();
data.features.forEach(f => {
  const name = f.properties.WADMKC || '';
  const upper = name.toUpperCase();
  if (targetSet.has(upper)) {
    matchedNames.add(name);
  } else {
    for (const t of targetSet) {
      if (upper.includes(t)) {
        matchedNames.add(name);
        break;
      }
    }
  }
});

fs.writeFileSync('matchedKecamatans.json', JSON.stringify(Array.from(matchedNames), null, 2));
console.log('Saved to matchedKecamatans.json');
